default:
  size: 1
  test: False
  signal:
    channelno: 3
    channel2:
      name: "tauetauh"
      triggers:
        electron: ["HLT_Ele24_eta2p1_WPTight_Gsf_TightChargedIsoPFTauHPS30_eta2p1_CrossL1","HLT_Ele32_WPTight_Gsf"]
        muon: null
        tau: null
      selections:
        electron:
          veto: False
          BDTLevel: 0.8
          ptLevel: 33
          absetaLevel: 2.1
          absdxyLevel: 0.045
          absdzLevel: 0.2
          count: 1
          outputs: 
            float:
              Electron_pt: Electron_pt
              Electron_mass: Electron_mass
              Electron_phi: Electron_phi
              Electron_eta: Electron_eta
              Electron_dxy: Electron_dxy
              Electron_dz: Electron_dz
              Electron_BDTID: Electron_mvaIso
            bool: null
            uint: null
        muon:
          veto: True
          ptLevel: 25
        tau: 
          veto: False
          ptLevel: 35
          absetaLevel: 2.3
          IDvsjetLevel: 5
          IDvsmuLevel: 4
          IDvseLevel: 3 
          absdzLevel: 0.2
          count: 1
          outputs:
            float:
              Tau_pt: Tau_pt
              Tau_eta: Tau_eta
              Tau_phi: Tau_phi
              Tau_mass: Tau_mass
              Tau_dxy: Tau_dxy
              Tau_dz: Tau_dz
            bool: null
            uint:
              Tau_IDvsjet: Tau_idDeepTau2018v2p5VSjet
              Tau_IDvsmu: Tau_idDeepTau2018v2p5VSmu
              Tau_IDvse: Tau_idDeepTau2018v2p5VSe
        pair:
          name: "ET"
          OS: True
          dRLevel: 0.5
    channel1:
      name: "taumtauh"
      triggers:
        electron: null
        muon: ["HLT_Mu25_TkMu0_Onia","HLT_IsoMu20_eta2p1_TightChargedIsoPFTauHPS27_eta2p1_TightID_CrossL1"]
        tau: null
      selections:
        electron:
          veto: True
          ptLevel: 25
        muon: 
          veto: False
          ptLevel: 25
          absetaLevel: 2.1
          IDLevel: True
          isoLevel: 0.15
          count: 1
          absdxyLevel: 0.045
          absdzLevel: 0.2
          outputs:
            float:
              Muon_dz: Muon_dz
              Muon_dxy: Muon_dxy
              Muon_phi: Muon_phi
              Muon_mass: Muon_mass
              Muon_eta: Muon_eta
              Muon_pt: Muon_pt
              Muon_isoID: Muon_pfRelIso04_all
            bool:
              Muon_tightID: Muon_tightID
            uint: null
        tau:
          veto: False
          ptLevel: 35
          absetaLevel: 2.3
          IDvsjetLevel: 5
          IDvsmuLevel: 4
          IDvseLevel: 3 
          absdzLevel: 0.2
          count: 1
          outputs:
            float:
              Tau_pt: Tau_pt
              Tau_eta: Tau_eta
              Tau_phi: Tau_phi
              Tau_mass: Tau_mass
              Tau_dxy: Tau_dxy
              Tau_dz: Tau_dz
            bool: null
            uint:
              Tau_IDvsjet: Tau_idDeepTau2018v2p5VSjet
              Tau_IDvsmu: Tau_idDeepTau2018v2p5VSmu
              Tau_IDvse: Tau_idDeepTau2018v2p5VSe
        pair:
          name: "MT" 
          OS: True
          dRLevel: 0.5
    channel3:
      name: "tauhtauh"
      selections:
        electron: null
        muon: null
        tau:
          veto: False
          ptLevel: 40
          absetaLevel: 2.3
          IDvsjetLevel: 5
          IdvsmuLevel: 1
          IDvseLevel: 2
          absdzLevel: 0.2
          count: 2
          outputs:
            float:
              Tau_pt: Tau_pt
              Tau_eta: Tau_eta
              Tau_phi: Tau_phi
              Tau_mass: Tau_mass
              Tau_dxy: Tau_dxy
              Tau_dz: Tau_dz
            bool: null
            uint:
              Tau_IDvsjet: Tau_idDeepTau2018v2p5VSjet
              Tau_IDvsmu: Tau_idDeepTau2018v2p5VSmu
              Tau_IDvse: Tau_idDeepTau2018v2p5VSe
        pair:
          name: "TT"
          OS: True
    commonsel:
      ak4jet:
        ptLevel: 20
        absetaLevel: 2.4
        dRLevel: 0.5
        count: 2
        overlapCheck: True
          
          
